name: Release new version

on:
  push:
    paths:
      - "release-all-versions.sh"
      - "release-latest-versions.sh"
      - ".github/workflows/release.yml"
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  release-new-stubs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Specify PHP version
          extensions: json, zip, xdebug
          coverage: none
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --ignore-platform-reqs

      - name: Set up Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Release new stubs from latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add error handling
          set -e
          bash release-latest-versions.sh
          # Check if any errors occurred during script execution
          if [ $? -ne 0 ]; then
            echo "Error occurred during stub generation"
            exit 1
          fi

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Generate stubs from latest version" || echo "No changes to commit"

      - name: Push changes
        if: steps.git-check.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git push origin HEAD:main
          git push --tags --force

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: Generate stubs from latest version
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-plugin-stubs
          delete-branch: true
          title: 'Generate stubs from latest version'
          body: |
            This PR updates the codebase with the latest changes from the WordPress Plugin Directory
            - Update from WordPress Plugin Directory
          labels: |
            update
            automated pr
          assignees: mralaminahamed
          draft: false

      - name: Check Output
        if: steps.git-check.outputs.changes == 'true'
        run: echo "Pull Request created successfully!"

      - name: No changes detected
        if: steps.git-check.outputs.changes != 'true'
        run: echo "No changes detected. Skipping PR creation."
